### ISSUE TITLE
SUIT input does not work on translate and scale

### ISSUE THREAD

**Issue by Whitecl4ws** [vrld/SUIT#58] opened 2017-08-02 19:56 UTC
I have a library that translates and scales love (to support multiple resolutions), and inputbox is scaled correctly but rendered unpressable, do you have any ideas why that is, and how one could fix it? I'm willing to do it myself, I just need a few pointers

**Comment by Sungray** [comment] 2017-09-17 13:10
You should use the suit.updateMouse method.

Something like this :

`   --update mouse to push scale
    local mouseX, mouseY = push:toGame(love.mouse.getX(), love.mouse.getY())
   suit.updateMouse(mouseX, mouseY, love.mouse.isDown(1))`

**Comment by vrld** [comment] 2017-10-28 09:56
Duplicate of #44 and #55.

**Closed by vrld** 2017-10-28 09:56 UTC
